gachaneitor/gachaneitor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls),
]

gachaneitor/web/urls.py
from django.urls import path

from .views import IndexView, RecetasView, HowToView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('howto/', HowToView.as_view(), name='howto'),
    path('recetas/', RecetasView.as_view(), name='recetas'),
]

gachaneitor/web/models.py
from django.db import models
import uuid
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Receta(models.Model):
    HORAS = 'h'
    MINUTOS = 'min'
    SEGUNDOS = 's'
    UNIDADES_TIEMPO_CHOICES = [
        (HORAS, 'Horas'),
        (MINUTOS, 'Minutos'),
        (SEGUNDOS, 'Segundos')
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length=128)
    descripcion = models.TextField()
    tmp_preparacion = models.IntegerField(default=0)
    ud_tmp_preparacion = models.CharField(max_length=3, choices=UNIDADES_TIEMPO_CHOICES)
    tmp_total = models.IntegerField(default=0)
    ud_tmp_total = models.CharField(max_length=3, choices=UNIDADES_TIEMPO_CHOICES)

    def __str__(self):
        return f'{self.nombre}'


class Ingrediente(models.Model):
    UNIDADES = 'ud'
    MILIGRAMOS = 'mg'
    GRAMOS = 'g'
    KILOGRAMOS = 'kg'
    MILILITROS = 'ml'
    LITROS = 'l'
    UNIDADES_CANTIDAD_CHOICES = [
        (UNIDADES, 'Unidades'),
        (MILIGRAMOS, 'Miligramos'),
        (GRAMOS, 'Gramos'),
        (KILOGRAMOS, 'Kilogramos'),
        (MILILITROS, 'Mililitros'),
        (LITROS, 'Litros')
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=128)
    cantidad = models.IntegerField(default=0)
    ud_cantidad = models.CharField(max_length=2, choices=UNIDADES_CANTIDAD_CHOICES)

    class Meta:
        unique_together = [['receta', 'nombre']]

    def __str__(self):
        return f'{self.nombre}'


class Paso(models.Model):
    CENTIGRADOS = 'ºC'
    FARENHEIT = 'ºF'
    UNIDADES_TEMPERATURA_CHOICES = [
        (CENTIGRADOS, 'Grados centígrados'),
        (FARENHEIT, 'Grados farenheit')
    ]
    MOVER = 'mover'
    PERSONA = 'persona'
    COCINAR = 'cocinar'
    TIPO_VERBO_CHOICES = [
        (COCINAR, 'Cocinar'),
        (PERSONA, 'Por la persona'),
        (MOVER, 'Mover')
    ]
    HORAS = 'h'
    MINUTOS = 'min'
    SEGUNDOS = 's'
    UNIDADES_TIEMPO_CHOICES = [
        (HORAS, 'Horas'),
        (MINUTOS, 'Minutos'),
        (SEGUNDOS, 'Segundos')
    ]
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
    num_paso = models.IntegerField(validators=[MinValueValidator(1)])
    verbo = models.CharField(max_length=128)
    tipo_verbo = models.CharField(max_length=64, choices=TIPO_VERBO_CHOICES)
    ingredientes = models.TextField()
    temperatura = models.IntegerField(null=True, blank=True)
    ud_temperatura = models.CharField(max_length=2, blank=True, choices=UNIDADES_TEMPERATURA_CHOICES)
    velocidad = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1), MaxValueValidator(9)])
    tiempo = models.IntegerField(null=True, blank=True)
    ud_tiempo = models.CharField(max_length=3, blank=True, choices=UNIDADES_TIEMPO_CHOICES)

    class Meta:
        unique_together = [['receta', 'num_paso']]

    def __str__(self):
        return f'{self.num_paso}'

    def save(self, *args, **kwargs):
        field_name = 'verbo'
        val = getattr(self, field_name, False)
        if val:
            setattr(self, field_name, val.capitalize())
        super(Paso, self).save(*args, **kwargs)

gachaneitor/web/views.py
from django.http import JsonResponse
from django.views.generic import TemplateView, ListView
import traceback

from web.models import Receta, Ingrediente, Paso
import json
from web.antlr.main import web_main

class IndexView(TemplateView):
    template_name = 'web/index.html'

    def post(self, request):
        text = request.POST['receta']
        
        try:
            recetas_dict = web_main(text)
            self.save_recetas(recetas_dict)
            return JsonResponse({'error': False, 'result': 'La receta ha sido almacenada correctamente'},
                                 status=200)
        except Exception as e:
            error = str(e)
            traceback.print_exc()
            return JsonResponse({'error': True, 'result': error}, status=200)
    
    def save_recetas(self, recetas):
        print(recetas)
        for receta in recetas:
            receta_instance = Receta(nombre=receta["nombre"], descripcion=receta["descripcion"], tmp_preparacion=receta["tiempo"]["preparacion"]["cantidad"], 
                                    ud_tmp_preparacion=receta["tiempo"]["preparacion"]["unidad"], 
                                    tmp_total=receta["tiempo"]["total"]["cantidad"], 
                                    ud_tmp_total=receta["tiempo"]["total"]["unidad"])
            
            receta_instance.save()
            for ingrediente in receta["ingredientes"]:
                ingrediente_instance = Ingrediente(receta=receta_instance, nombre=ingrediente,
                            cantidad=receta["ingredientes"][ingrediente]["cantidad"],
                            ud_cantidad=receta["ingredientes"][ingrediente]["unidad"])
                ingrediente_instance.save()

            num_paso=1
            for paso in receta["pasos"]:
                tipo_verbo = paso["tipo_verbo"]
                ingredientes_str = ""
                for ingrediente in paso["ingredientes"]:
                    ingredientes_str +=  str(paso["ingredientes"][ingrediente]["cantidad"]) + " " + paso["ingredientes"][ingrediente]["unidad"] + " de " + ingrediente + ", " 
                ingredientes_str = ingredientes_str[:-2]

                if tipo_verbo == "persona":
                    paso_instance = Paso(receta=receta_instance, num_paso=num_paso, 
                                        verbo=paso["verbo"], tipo_verbo=tipo_verbo, ingredientes=ingredientes_str)
                    paso_instance.save()
                elif tipo_verbo == "cocinar":
                    paso_instance = Paso(receta=receta_instance, num_paso=num_paso, verbo=paso["verbo"], 
                                            tipo_verbo=tipo_verbo, ingredientes=ingredientes_str, 
                                            temperatura=paso["temperatura"]["cantidad"], 
                                            ud_temperatura=paso["temperatura"]["unidad"], 
                                            tiempo=paso["tiempo"]["cantidad"], 
                                            ud_tiempo=paso["tiempo"]["unidad"])
                    paso_instance.save()
                elif tipo_verbo == "mover":
                    paso_instance = Paso(receta=receta_instance, num_paso=num_paso, 
                                        verbo=paso["verbo"], tipo_verbo=tipo_verbo, 
                                        ingredientes=ingredientes_str, 
                                        velocidad=int(paso["velocidad"]),
                                        tiempo=paso["tiempo"]["cantidad"], 
                                        ud_tiempo=paso["tiempo"]["unidad"])
                    paso_instance.save()              
                num_paso += 1
                

            
            

class RecetasView(ListView):
    template_name = 'web/recetas.html'
    context_object_name = 'recetas'
    model = Receta
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().order_by('nombre')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ingredientes'] = Ingrediente.objects.all().order_by('nombre')
        context['pasos'] = Paso.objects.all().order_by('num_paso')
        return context

class HowToView(TemplateView):
    template_name='web/howto.html'

gachaneitor/web/templates/web/howto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cómo crear una receta</title>
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}">
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'web/scss/estilos.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'web/res/icono.png' %}">
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">GACHANEITOR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/howto">Cómo crear una receta</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Introducir receta </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/recetas">Recetario</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="jumbotron">
        <div classs="container">
            <h1>Cómo crear una receta</h1>
            <p>Es importante saber qué tipo de pasos se deben seguir para añadir una receta a este repositorio.</p>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h2>Modo de introducción</h2>
                <p>Existen dos modos para introducir las recetas:</p>
                <ul>
                    <li>Importando un archivo de texto desde la máquina.</li>
                    <li>En la propia página, escribir la receta a mano en un área de texto.</li>
                </ul>
                <p>En caso de que se introduzcan ambas opciones, se le dará mayor prioridad al archivo subido, por lo que el procesador analizará la receta del archivo txt.</p>
            </div>
            <div class="col-md-6 p-4">
                <div class="text-center">
                    {% load static %}
                    <img src="{% static 'web/res/upload.png' %}" class="img-thumbnail rounded-circle shadow w-50" alt="...">
                </div>
            </div>
        </div>


        <div class='row'>
        <div class='col-lg-12 px-m-5'>
        <hr>
       </div>
       </div>

        <div class="row align-items-center">
            <div class="col-md-6 jumbotron">
                <samp>
                    <strong>receta</strong> {<br>
                        &emsp;&emsp;<strong>nombre</strong> "Puré"<br>
                        &emsp;&emsp;<strong>descripcion</strong> [Esta es una receta muy rica]<br>
                        &emsp;&emsp;<strong>tiempo</strong> {<br>
                            &emsp;&emsp;&emsp;&emsp;<em>total</em> 20 min /* Comprobar con suma de tiempos parciales (Opcional) */<br>
                            &emsp;&emsp;&emsp;&emsp;<em>preparacion</em> 5 min /* No hace falta comprobar, porque son verbos de persona */<br>
                        &emsp;&emsp;}<br>
                        <br>
                        &emsp;&emsp;<strong>ingredientes</strong> {<br>
                            &emsp;&emsp;&emsp;&emsp;"Calabaza": 2 ud;<br>
                            &emsp;&emsp;&emsp;&emsp;"Calabacín": 2 ud;<br>
                        &emsp;&emsp;}<br>
                        <br>
                        &emsp;&emsp;<strong>pasos</strong> {<br>
                            &emsp;&emsp;&emsp;&emsp;- <em>pelar</em> "Calabacín": 2 ud; "Calabaza": 2 ud;<br>
                            &emsp;&emsp;&emsp;&emsp;- <em>trocear</em> "Calabacín": 2 ud; "Calabaza": 2 ud;<br>
                            &emsp;&emsp;&emsp;&emsp;- <em>sofreir</em> "Calabacín": 2 ud; "Calabaza": 2 ud; 10 min temperatura 20ºC<br>
                            &emsp;&emsp;&emsp;&emsp;- <em>triturar</em> "Calabacín": 2 ud; "Calabaza": 2 ud; 10 min velocidad 02<br>
                        &emsp;&emsp;}<br>
                    }
                </samp>
            </div>

            <div class="col-md-6 p-4">
                <h2>Cómo escribir la receta</h2>
                <p><i>Gachalanguage</i> es un lenguaje específico del dominio en el que cadaa receta se define de la siguiente forma:</p>
                <ul>
                    <li>La palabra <code>receta</code> junto a dos llaves (una abierta y una cerrada) que indica el comienzo de una receta
                        (ya que pueden existir varias en la misma cadena).</li>
                    <li>Dentro de estas llaves, están situadas las partes que conforman una receta en el siguiente orden fijo:
                        <ul>
                            <li>
                                El <strong>nombre</strong> de la receta, que se define mediante la palabra <code>nombre</code> (opcional) y a continuación el
                                nombre de la misma entre comillas (e.g. nombre "Puré").
                            </li>
                            <li>
                                La <strong>descripción</strong> de esta receta, que se define mediante la palabra <code>descripcion</code> (opcional) seguida
                                de una descripción entre corchetes.
                            </li>
                            <li>
                                El <strong>tiempo</strong> de la receta, que se define mediante la palabra <code>tiempo</code> (opcional) seguida de dos llaves. Entre ellas:
                                <ul>
                                    <li>
                                        El <strong>tiempo total</strong> se declara mediante la palabra <code>total</code> junto con el que la máquina invierte en procesar los alimentos.
                                        Seguido de esto viene una unidad de tiempo (<code>h</code>, <code>min</code>, <code>seg</code>).
                                    </li>
                                    <li>
                                        El <strong>tiempo de preparación</strong> se declara mediante la palabra <code>preparacion</code> junto con el tiempo invertido en la misma (<code>h</code>, <code>min</code>, <code>seg</code>).
                                    </li>
                                </ul>
                            </li>
                            <li>
                                Los <strong>ingredientes</strong> es la sección donde se declaran todos los ingredientes usados en la receta en forma de lista. Esta sección se define
                                con la palabra <code>ingredientes</code> (opcional), seguida de una llave abierta y otra cerrada. Se puede separar los ingredientes mediante punto y coma
                                aunque no es necesario. También, cada ingrediente debe ir acompañado de su cantidad de masa (<code>kg</code>, <code>g</code>, <code>mg</code>),
                                volumen (<code>l</code>, <code>ml</code>) y unidad (<code>ud</code>).
                            </li>
                            <li>
                                Los <strong>pasos</strong> se definen con la palabra <code>pasos</code>, lo cual es opcional, seguido de llaves. Dentro de él, cada paso se define por un
                                <strong>guion</strong>, un <strong>verbo</strong> y unos <strong>ingredientes</strong> con sus respectivas <strong>cantidades</strong>.
                                Aparte de esto, según el significado del verbo, podremos añadir <strong>temperatura</strong> y <strong>velocidad</strong>.
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>

                <p>Además se pueden introducir comentarios entre los símbolos /* y */ que, aunque la web no los muestre, pueden ser de utilidad para almacenar trucos 
                y/o información adicional. <i> Para más información, véase la documentación del lenguaje.</i> </p>

                <p> A continuación se muestran los tipos de verbos permitidos a la hora de describir el paso de una receta. </p>

        </div>

                
        <div class='row'> <div class='col-lg-12 px-m-5'> <hr> </div> </div>
        
        <h2 style="text-align: center;">Tipos de verbos permitidos en los pasos </h2>
        <br>
        <div class="row">
            <div class="col-md-4">
            <table class="table">
                <thead>
                    <tr class="table-primary">
                    <th scope="col">Verbo de movimiento <br> (usan tiempo y velocidad)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>licuar</td>
                    </tr>
                    <tr>
                        <td>triturar</td>
                    </tr>
                    <tr>
                        <td>batir</td>
                    </tr>
                    <tr>
                        <td>dejar reposar</td>
                    </tr>
                    <tr>
                        <td>amasar</td>
                    </tr>
                    <tr>
                        <td>mezclar</td>
                    </tr>
                </tbody>
            </table>
            </div>
            
            <div class="col-md-4">
            <table class="table">
                <thead>
                    <tr class="table-primary">
                    <th scope="col">Verbo de cocción <br> (usan tiempo y temperatura) </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>cocinar al vapor</td>
                    </tr>
                    <tr>
                        <td>escalfar</td>
                    </tr>
                    <tr>
                        <td>hervir</td>
                    </tr>
                    <tr>
                        <td>guisar</td>
                    </tr>
                    <tr>
                        <td>sofreir</td>
                    </tr>
                </tbody>
            </table>
            </div>

            <div class="col-md-4">
            <table class="table">
                <thead>
                    <tr class="table-primary">
                    <th scope="col">Verbo de persona</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>pelar</td>
                    </tr>
                    <tr>
                        <td>trocear</td>
                    </tr>
                    <tr>
                        <td>moler</td>
                    </tr>
                </tbody>
            </table>
            </div>

        </div>
    </div>
    
    <!-- Footer -->
    <footer class="mt-auto font-small pt-4">
        <div class="container-fluid text-center text-md-left bg-primary" >
            <div class="row">
                <div class="col-md-7 mt-md-0 mt-3">
                    <p> </p>
                </div>
                <div class="col-md-7 mt-md-0 mt-3">
                    <!-- Content -->
                    <h5 class="text-uppercase text-light">Información</h5>
                    <p class="text-light"> Herramienta desarrollada por Raúl Bernalte,
                        Enrique Cepeda, Elena Hervás y Elena María Ruiz</p>
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
            </div>
        </div>
    </footer>
    <!-- Footer -->
    
    {% load static %}
    <script src="{% static 'web/js/jquery-3.5.1.min.js' %}"></script>
    {% load static %}
    <script src="{% static 'web/js/popper.min.js' %}"></script>
    {% load static %}
    <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
</body>
</html>

gachaneitor/web/templates/web/recetas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recetario</title>
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}">
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'web/scss/estilos.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'web/res/icono.png' %}">
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">GACHANEITOR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                 <li class="nav-item">
                    <a class="nav-link" href="/howto">Cómo crear una receta</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Introducir receta</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/recetas">Recetario</a>
                </li>
            </ul>
        </div>
    </nav>
    <br> 
    <section id="recetas">
        {% for receta in recetas %}

            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{ receta.nombre }}</h4>
                        <h5 class="card-subtitle"> <i> Descripción </i> </h5>
                        <p class="card-text" style="padding-left: 20px">{{ receta.descripcion }}</p>
                        <h5 class="card-subtitle"> <i> Tiempo </i> </h5>
                        <ul class="card-text">
                            <li class="card-text"><strong>Preparación: </strong>{{ receta.tmp_preparacion}} {{ receta.ud_tmp_preparacion }}.</li>
                            <li class="card-text"><strong>Total: </strong>{{ receta.tmp_preparacion}} {{ receta.ud_tmp_preparacion }}.</li>
                        </ul>
                        <h5 class="card-subtitle"> <i> Ingredientes </i> </h5>
                        <ul class="card-text">
                            {% for ingrediente in receta.ingrediente_set.all %}
                                <li class="card-text"><strong>{{ ingrediente.nombre }}: </strong>{{ ingrediente.cantidad }} {{ ingrediente.ud_cantidad }}.</li>
                            {% endfor %}
                        </ul>
                        <h5 class="card-subtitle"> <i> Pasos </i></h5>
                        <ol class="card-text">
                            {% for paso in receta.paso_set.all %}
                                {% if paso.temperatura %}
                                <li class="card-text">{{ paso.verbo }} {{ paso.ingredientes }},
                                a una temperatura de {{ paso.temperatura }} {{ paso.ud_temperatura }} durante {{ paso.tiempo }} {{paso.ud_tiempo}}.</li>
                                {% elif paso.velocidad %}
                                <li class="card-text">{{ paso.verbo }} {{ paso.ingredientes }},
                                    a velocidad {{ paso.velocidad }} durante {{ paso.tiempo }} {{paso.ud_tiempo}}.</li>
                                {% else %}
                                <li class="card-text">{{ paso.verbo }} {{ paso.ingredientes }}.</li>
                                {% endif %}
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
    </section>

    <section id="pagination">
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo; Primero</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">
                            Anterior</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        {{ page_obj.previous_page_number }}</a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ page_obj.number }}">
                        {{ page_obj.number }}</a>
                    </li>
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        {{ page_obj.next_page_number }}</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Último &raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>

    <!-- Footer -->
    <footer class="mt-auto font-small pt-4">
        <div class="container-fluid text-center text-md-left bg-primary" >
            <div class="row">
                <div class="col-md-7 mt-md-0 mt-3">
                    <p> </p>
                </div>
                <div class="col-md-7 mt-md-0 mt-3">
                    <h5 class="text-uppercase text-light">Información</h5>
                    <p class="text-light">Herramienta desarrollada por Raúl Bernalte,
                        Enrique Cepeda, Elena Hervás y Elena María Ruiz</p>
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
            </div>
        </div>
    </footer>
    <!-- Footer -->

    {% load static %}
    <script src="{% static 'web/js/jquery-3.5.1.min.js' %}"></script>
    {% load static %}
    <script src="{% static 'web/js/popper.min.js' %}"></script>
    {% load static %}
    <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
</body>
</html>